[SQUASH] mm: mglru: Fix mis-merge for 4.19
This commit fixes the following error messages

../mm/swap.c:591:13: error: implicit declaration of function 'page_lru_base_type' [-Werror,-Wimplicit-function-declaration]
  591 |                 int lru = page_lru_base_type(page);
      |                           ^
../mm/swap.c:593:40: error: too many arguments to function call, expected 2, have 3
  593 |                 del_page_from_lru_list(page, lruvec, lru + LRU_ACTIVE);
      |                 ~~~~~~~~~~~~~~~~~~~~~~               ^~~~~~~~~~~~~~~~
../include/linux/mm_inline.h:311:29: note: 'del_page_from_lru_list' declared here
  311 | static __always_inline void del_page_from_lru_list(struct page *page,
      |                             ^                      ~~~~~~~~~~~~~~~~~~
  312 |                                 struct lruvec *lruvec)
      |                                 ~~~~~~~~~~~~~~~~~~~~~
../mm/swap.c:596:38: error: too many arguments to function call, expected 2, have 3
  596 |                 add_page_to_lru_list(page, lruvec, lru);
      |                 ~~~~~~~~~~~~~~~~~~~~               ^~~
../include/linux/mm_inline.h:287:29: note: 'add_page_to_lru_list' declared here
  287 | static __always_inline void add_page_to_lru_list(struct page *page,
      |                             ^                    ~~~~~~~~~~~~~~~~~~
  288 |                                 struct lruvec *lruvec)
      |                                 ~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Santhosh <san8754513543@gmail.com>

mm: mglru: Fix some missing function declarations and pointer errors

Signed-off-by: Santhosh <san8754513543@gmail.com>