sched/debug: Remove entity_eligible usage from print_task()
Since CONFIG_SCHED_WALT is not enabled, entity_eligible and cfs_rq_of are not defined, causing implicit declaration errors.

This fixes the following error:
./kernel/sched/debug.c:321:3: error: implicit declaration of function 'entity_eligible' [-Werror,-Wimplicit-function-declaration]
  321 |                 entity_eligible(cfs_rq_of(&p->se), &p->se) ? 'E' : 'N',
      |                 ^
../kernel/sched/debug.c:321:19: error: implicit declaration of function 'cfs_rq_of' [-Werror,-Wimplicit-function-declaration]
  321 |                 entity_eligible(cfs_rq_of(&p->se), &p->se) ? 'E' : 'N',

Change-Id: Idfffbbda17415fdcec7dedc37d8ae0fa32cf6925
Signed-off-by: angelomds42 <angelomds42@gmail.com>